image: vcmt/docker-in-docker-aws:latest

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
- docker:19.03.1-dind

stages:
  - test

build_and_test:
  stage: test
  script:
  - docker-compose up --build dqp
